"""``pastime.mlb`` — the MLB Stats API (statsapi.mlb.com) subpackage.

A fully featured, pure pass-through wrapper: every endpoint function returns the
raw JSON ``dict`` exactly as the API produced it. Transport (retry/backoff,
4xx-vs-5xx handling) is delegated to :mod:`pastime.http`; MLB-specific input
problems raise :class:`pastime.exceptions.MLBStatsError` /
:class:`pastime.exceptions.ValidationError`.
"""

from __future__ import annotations

from pastime.mlb.discovery import (
    get_baseball_stats,
    get_event_types,
    get_game_status,
    get_game_types,
    get_hit_trajectories,
    get_job_types,
    get_languages,
    get_league_leader_types,
    get_metrics,
    get_pitch_types,
    get_platforms,
    get_positions,
    get_roster_types,
    get_schedule_event_types,
    get_situation_codes,
    get_sky,
    get_sports_discovery,
    get_standings_types,
    get_stat_groups,
    get_stat_types,
    get_wind_direction,
)
from pastime.mlb.games import (
    get_boxscore,
    get_color_diffpatch,
    get_color_feed,
    get_color_timestamps,
    get_context_metrics,
    get_game_changes,
    get_game_content,
    get_gamefeed,
    get_gamefeed_diffpatch,
    get_gamefeed_timestamps,
    get_linescore,
    get_playbyplay,
    get_postseason_schedule,
    get_postseason_series,
    get_schedule,
    get_tied_games,
    get_win_probability,
)
from pastime.mlb.misc import (
    get_attendance,
    get_award_recipients,
    get_broadcasts,
    get_conferences,
    get_datacasters,
    get_derby_bracket,
    get_derby_pool,
    get_divisions,
    get_draft,
    get_draft_prospects,
    get_game_pace,
    get_high_low,
    get_home_run_derby,
    get_league,
    get_leagues,
    get_official_scorers,
    get_season,
    get_seasons,
    get_sport,
    get_sport_players,
    get_sports,
    get_standings,
    get_transactions,
    get_umpires,
    get_uniforms_game,
    get_uniforms_team,
    get_venue,
    get_venues,
)
from pastime.mlb.people import (
    find_player,
    get_free_agents,
    get_people,
    get_person,
    get_player_changes,
    get_player_stats_all_sports,
    resolve_player_id,
    search_player_matches,
    search_players,
)
from pastime.mlb.stats import (
    build_stats_hydrate,
    get_stat_leaders,
    get_stats,
    get_streaks,
)
from pastime.mlb.stats_api import mlb_api
from pastime.mlb.teams import (
    get_roster,
    get_team,
    get_team_affiliates,
    get_team_alumni,
    get_team_history,
    get_team_leaders,
    get_team_specific_leaders,
    get_team_specific_stats,
    get_team_stats,
    get_teams,
    resolve_team_id,
)

__all__ = [  # noqa: RUF022  -- grouped by module for integration re-export
    # stats_api
    "mlb_api",
    # people
    "get_people",
    "get_person",
    "search_players",
    "search_player_matches",
    "find_player",
    "resolve_player_id",
    "get_player_changes",
    "get_free_agents",
    "get_player_stats_all_sports",
    # teams
    "get_teams",
    "get_team",
    "get_team_history",
    "get_team_stats",
    "get_team_leaders",
    "get_team_affiliates",
    "get_roster",
    "get_team_specific_leaders",
    "get_team_specific_stats",
    "get_team_alumni",
    "resolve_team_id",
    # games
    "get_schedule",
    "get_gamefeed",
    "get_gamefeed_diffpatch",
    "get_gamefeed_timestamps",
    "get_boxscore",
    "get_linescore",
    "get_playbyplay",
    "get_game_content",
    "get_context_metrics",
    "get_win_probability",
    "get_color_feed",
    "get_color_diffpatch",
    "get_color_timestamps",
    "get_game_changes",
    "get_postseason_schedule",
    "get_postseason_series",
    "get_tied_games",
    # stats
    "build_stats_hydrate",
    "get_stats",
    "get_stat_leaders",
    "get_streaks",
    # misc
    "get_draft",
    "get_draft_prospects",
    "get_award_recipients",
    "get_transactions",
    "get_venues",
    "get_venue",
    "get_standings",
    "get_leagues",
    "get_league",
    "get_divisions",
    "get_seasons",
    "get_season",
    "get_attendance",
    "get_sports",
    "get_sport",
    "get_sport_players",
    "get_umpires",
    "get_official_scorers",
    "get_datacasters",
    "get_broadcasts",
    "get_conferences",
    "get_high_low",
    "get_home_run_derby",
    "get_derby_bracket",
    "get_derby_pool",
    "get_game_pace",
    "get_uniforms_game",
    "get_uniforms_team",
    # discovery
    "get_stat_types",
    "get_stat_groups",
    "get_game_types",
    "get_positions",
    "get_situation_codes",
    "get_metrics",
    "get_league_leader_types",
    "get_sports_discovery",
    "get_baseball_stats",
    "get_roster_types",
    "get_standings_types",
    "get_game_status",
    "get_pitch_types",
    "get_hit_trajectories",
    "get_event_types",
    "get_schedule_event_types",
    "get_wind_direction",
    "get_sky",
    "get_job_types",
    "get_languages",
    "get_platforms",
]
