"""Baseball Savant (Statcast) data access.

Three modules, all returning raw ``list[dict]`` (HTML-backed leaderboards return
parsed JSON):

- :mod:`fungo.statcast.search` — pitch-level search, matchup/team/game
  convenience queries, and per-arsenal aggregation.
- :mod:`fungo.statcast.leaderboards` — the leaderboard registry, a
  ``year_format``-aware fetcher, typed wrappers for ~33 boards, percentile
  rankings, and HTML-backed scrapers (park factors, hot stove, rolling windows).
- :mod:`fungo.statcast.physics` — Nathan (2021) derived spin columns and
  spin-axis-to-clock conversion.
"""

from __future__ import annotations

from fungo.statcast.leaderboards import (
    LEADERBOARDS,
    active_spin_year,
    describe_leaderboard,
    fetch_leaderboard,
    get_abs_challenges,
    get_active_spin,
    get_arm_angles,
    get_arm_strength,
    get_baserunning,
    get_baserunning_run_value,
    get_basestealing_run_value,
    get_bat_tracking,
    get_batted_ball,
    get_catch_probability,
    get_catcher_blocking,
    get_catcher_framing,
    get_catcher_stance,
    get_catcher_throwing,
    get_custom_leaderboard,
    get_directional_oaa,
    get_exit_velocity_barrels,
    get_expected_statistics,
    get_fielding_run_value,
    get_game_scores,
    get_home_runs,
    get_hot_stove,
    get_leaderboard,
    get_outfield_jump,
    get_outs_above_average,
    get_park_factors,
    get_percentile_rankings,
    get_pitch_arsenal_stats,
    get_pitch_arsenals,
    get_pitch_movement,
    get_pitch_tempo,
    get_pitcher_running_game,
    get_poptime,
    get_rolling_windows,
    get_running_splits,
    get_spin_direction,
    get_sprint_speed,
    get_swing_path_attack_angle,
    get_swing_take,
    get_swing_timing_miss_distance,
    get_timer_infractions,
    get_year_to_year,
    list_leaderboards,
)
from fungo.statcast.physics import add_spin_columns, axis_to_clock
from fungo.statcast.search import (
    aggregate_pitcher_arsenal,
    get_pitcher_arsenal,
    resolve_team,
    search_game,
    search_matchup,
    search_pitches,
    search_team,
    statcast_search,
)

__all__ = [
    "LEADERBOARDS",
    "active_spin_year",
    "add_spin_columns",
    "aggregate_pitcher_arsenal",
    "axis_to_clock",
    "describe_leaderboard",
    "fetch_leaderboard",
    "get_abs_challenges",
    "get_active_spin",
    "get_arm_angles",
    "get_arm_strength",
    "get_baserunning",
    "get_baserunning_run_value",
    "get_basestealing_run_value",
    "get_bat_tracking",
    "get_batted_ball",
    "get_catch_probability",
    "get_catcher_blocking",
    "get_catcher_framing",
    "get_catcher_stance",
    "get_catcher_throwing",
    "get_custom_leaderboard",
    "get_directional_oaa",
    "get_exit_velocity_barrels",
    "get_expected_statistics",
    "get_fielding_run_value",
    "get_game_scores",
    "get_home_runs",
    "get_hot_stove",
    "get_leaderboard",
    "get_outfield_jump",
    "get_outs_above_average",
    "get_park_factors",
    "get_percentile_rankings",
    "get_pitch_arsenal_stats",
    "get_pitch_arsenals",
    "get_pitch_movement",
    "get_pitch_tempo",
    "get_pitcher_arsenal",
    "get_pitcher_running_game",
    "get_poptime",
    "get_rolling_windows",
    "get_running_splits",
    "get_spin_direction",
    "get_sprint_speed",
    "get_swing_path_attack_angle",
    "get_swing_take",
    "get_swing_timing_miss_distance",
    "get_timer_infractions",
    "get_year_to_year",
    "list_leaderboards",
    "resolve_team",
    "search_game",
    "search_matchup",
    "search_pitches",
    "search_team",
    "statcast_search",
]
